apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: { { .Values.leaderboard.name } }
spec:
  schedule: { { .Values.leaderboard.schedule } }
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: { { .Values.volume.name } }
              secret:
                secretName: { { .Values.volume.secretName } }
          containers:
            - name: { { .Values.leaderboard.containerName } }
              image: { { .Values.leaderboard.image } }
              command: ["bash", "-c"]
              imagePullPolicy: Always
              env:
                - name: PGCONN
                  value: { { .Values.postgresql.postgresUri } }
              volumeMounts:
                - name: { { .Values.volume.name } }
                  mountPath: { { .Values.volume.mountPath } }
                  subPath: { { .Values.volume.subPath } }
                  readOnly: true
