testnetName: "coda-testnet"
coda: 
  rpcPort: 8301
  hostPort: 10001
  graphqlPort: 3085
  genesis: 
    active: true
    k: 10
    delta: 3
    txpool_max_size: 3000
    genesis_state_timestamp: "2020-02-25 10:00:00-07:00" 
  image: codaprotocol/coda-daemon:0.0.12-beta-release-0.0.13-beta-573a55d
  seedPeers: 
    - /ip4/35.185.66.37/tcp/10105/ipfs/12D3KooWQ7Pz3SPizarzx9ZhCJ6jNmQ2iDPgHQxVzRzqYU2SgRSd     
    - /ip4/35.237.214.144/tcp/10120/ipfs/12D3KooWGtjWnCcvkaSEbKuNbPivEogxqtLWcsJiQtURydptvrsA

proxy: 
  fullname: "graphql-proxy-{{ .Values.testnetName }}"
  active: true
  image: codaprotocol/graphql-proxy:0.0.10
  externalPort: 8000

