apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testnet-points-api-cron
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: api
            image: gcr.io/o1labs-192920/testnet-points-api:0.0.7
            command: ["bash", "-c"]
            args: 
              - |
                ./manage.py runcrons
            env:
              - name: DJANGO_SECRET_KEY
                value: "foobarbatPRODUCTION"
              - name: DATABASE_URL
                value: "postgres://postgres:vxJAfEnryhPoG5xA@testnet-points-db-svc:5432/postgres"
              - name: DJANGO_AWS_ACCESS_KEY_ID
                value: "AKIAW3PMVC5VEUV7Z75L"
              - name: DJANGO_AWS_SECRET_ACCESS_KEY
                value: "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"
              - name: DJANGO_AWS_STORAGE_BUCKET_NAME
                value: testnet-points-api-static
            volumeMounts:
              - name: testnet-points-api-sql-instance-credentials
                mountPath: /secrets/credentials.json
                subPath: sql-instance-credentials.json
                readOnly: true
            imagePullPolicy: Always
          volumes:
            - name: testnet-points-api-sql-instance-credentials
              secret:
                secretName: testnet-points-api-sql-instance-credentials
      
          