apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-one
  labels:
    app: producer-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-one
  template:
    metadata:
      labels:
        app: producer-one
        testnet: {{ .Values.testnetName }}
        role: block-producer
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10000'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: fix-perms
        image: busybox
        command:
        - sh
        - -c
        - /bin/cp /keys/* /wallet-keys && /bin/chmod 0700 /wallet-keys
        volumeMounts:
        - name: private-keys
          mountPath: "/keys/"
          readOnly: true
        - name: wallet-keys
          mountPath: /wallet-keys
        securityContext:
          runAsUser: 0
      containers:
      - name: coda
        resources:
          limits:
            memory: 10.5Gi
          requests:
            memory: 8Gi
        image: {{ .Values.codaImage }}
        command: ["coda"]
        args: [ "daemon",
          "-log-level", "Trace",
          "-log-json",
          "-config-directory", "/root/coda-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-discovery-port", "$(DAEMON_DISCOVERY_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-propose-key", "/root/wallet-keys/key",
          {{- range .Values.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end }}
        ]
        env:
          - name: DAEMON_REST_PORT
            value: "3085"
          - name: DAEMON_CLIENT_PORT
            value: "8301"
          - name: DAEMON_METRICS_PORT
            value: "10000"
          - name: DAEMON_EXTERNAL_PORT
            value: {{ add .Values.startingPorts 1 | quote }}
          - name: DAEMON_DISCOVERY_PORT
            value: {{ add .Values.startingPorts 2 | quote }}
          - name: CODA_PRIVKEY_PASS
            value: {{ .Values.codaPrivkeyPass | quote }}
          # This should work but doesn't, need to pass in a file for now
          # - name: CODA_PROPOSE_KEY
          #   value: "tdNDjjAwyjgvNgU1x8uWs1n44H8vK7UGrRLvXzkcv8iC3Jw9A1B1UDUZndgBZh6zTb23pNatt7ujfTbCVjiihTZRMJcErZSkz93qE5Ue5VpAJsvaQvpHQGj3XexP2fK6i6xMfQArSvcXWV"
        ports:
          - containerPort: {{ add .Values.startingPorts 1 }}
            hostPort: {{ add .Values.startingPorts 1 }}
            protocol: TCP
          - containerPort: {{ add .Values.startingPorts 2 }}
            hostPort: {{ add .Values.startingPorts 2 }}
            protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: wallet-keys
          mountPath: /root/wallet-keys
      volumes:
      - name: private-keys
        secret:
          secretName: block-producer-one-key
          defaultMode: 256
          items:
          - key: key
            path: key
          - key: pub
            path: key.pub
      - name: wallet-keys
        emptyDir: {}