apiVersion: apps/v1
kind: Deployment
metadata:
  name: snark-worker-{{ trunc -6 .Values.publicKey | lower }}
  labels:
    app: snark-worker-{{ trunc -6 .Values.publicKey | lower }}
spec:
  replicas: {{ .Values.numReplicas }}
  selector:
    matchLabels:
      app: snark-worker-{{ trunc -6 .Values.publicKey | lower }}
  template:
    metadata:
      labels:
        app: snark-worker-{{ trunc -6 .Values.publicKey | lower }}
        testnet: {{ $.Values.testnetName }}
        role: snark-worker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: coda
        resources:
          limits:
            memory: 6.0Gi
          requests:
            memory: 2.0Gi
            cpu: 1
        image: {{ $.Values.codaImage }}
        command: ["/usr/bin/dumb-init", "/init_coda.sh"]
        args: [ "daemon",
          "-log-level", "Trace",
          "-log-json",
          "-config-directory", "/root/coda-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-run-snark-worker", "$(CODA_SNARK_KEY)", 
          "-snark-worker-fee", "$(CODA_SNARK_FEE)",
          {{- range $.Values.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end }}
        ]
        env:
          - name: DAEMON_REST_PORT
            value: "3085"
          - name: DAEMON_CLIENT_PORT
            value: "8301"
          - name: DAEMON_METRICS_PORT
            value: "10000"
          - name: CODA_SNARK_KEY
            value: {{ .Values.publicKey | quote }}
          - name: CODA_SNARK_FEE
            value: {{ .Values.snarkFee | quote }}
          - name: DAEMON_EXTERNAL_PORT
            value: {{ .Values.hostPort | quote }}
          - name: CODA_PRIVKEY_PASS
            value: {{ .Values.codaPrivkeyPass | quote }}
        ports:
          - containerPort: {{ .Values.hostPort }}
            hostPort: {{ .Values.hostPort }}
            protocol: TCP
        imagePullPolicy: Always
