{{ range $i, $e := until (.Values.blockProducer.numProducers | int)}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}
  labels:
    app: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}
  template:
    metadata:
      labels:
        app: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}
        testnet: {{ $.Values.testnetName }}
        role: block-producer
        class: {{ $.Values.blockProducer.class }}
        version: {{ (split ":" $.Values.coda.image)._1 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: fix-perms
        image: busybox
        command:
        - sh
        - -c
        - /bin/cp /keys/* /wallet-keys && /bin/chmod 0700 /wallet-keys
        volumeMounts:
        - name: private-keys
          mountPath: "/keys/"
          readOnly: true
        - name: wallet-keys
          mountPath: /wallet-keys
        securityContext:
          runAsUser: 0
      - name: install-key
        image: {{ $.Values.coda.image }}
        command:
        - bash
        - -c
        - coda accounts import -config-directory /root/.coda-config -privkey-path /root/wallet-keys/key
        volumeMounts:
        - name: wallet-keys
          mountPath: /root/wallet-keys
        - name: config-dir
          mountPath: /root/.coda-config
        env: 
          - name: CODA_PRIVKEY_PASS
            value: {{ $.Values.blockProducer.codaPrivkeyPass | quote }} 
      containers:
      {{ if $.Values.agent.active }}
      - name: user-agent
        resources:
          requests:
            memory: 512m
            cpu: 0.1
        image: {{ $.Values.agent.image }}
        command: ["bash"]
        args: ["-c", {{ range $.Values.agent.command }} {{- . | quote }}, {{end}} ]
        env: 
          - name: AGENT_SEND_EVERY_MINUTES
            value: "10"
          - name: CODA_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.blockProducer.keySecretTemplatePrefix }}-{{ add $i 1 $.Values.labelOffset }}-key
                key: pub
          - name: CODA_PRIVKEY_PASS
            value: {{ $.Values.blockProducer.codaPrivkeyPass | quote }}
          - name: PYTHONUNBUFFERED
            value: "1"
        ports: 
          - name: metrics
            containerPort: 8000
        imagePullPolicy: Always
      {{ end -}}
      - name: coda
        resources:
          limits:
            memory: 6.0Gi
          requests:
            memory: 2.0Gi
            cpu: 1
        image: {{ $.Values.coda.image }}
        command: ["/usr/bin/dumb-init", "/root/init_coda.sh"]
        args: [ "daemon",
          "-log-level", "Trace",
          "-log-json",
          "-config-directory", "/root/.coda-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-insecure-rest-server",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-block-producer-key", "/root/wallet-keys/key",
          {{- if $.Values.coda.genesis.active }}
          "-genesis-constants", "/genesis_constants/genesis_constants.json",
          {{- end -}}
          {{- range $.Values.coda.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end -}}
        ]
        env:
          - name: DAEMON_REST_PORT
            value: "3085"
          - name: DAEMON_CLIENT_PORT
            value: "8301"
          - name: DAEMON_METRICS_PORT
            value: "10000"
          - name: DAEMON_EXTERNAL_PORT
            value: {{ add $.Values.blockProducer.startingPorts $i $.Values.blockProducer.labelOffset | quote }}
          - name: CODA_PRIVKEY_PASS
            value: {{ $.Values.blockProducer.codaPrivkeyPass | quote }}
        ports:
          - containerPort: {{ add $.Values.blockProducer.startingPorts $i $.Values.blockProducer.labelOffset }}
            hostPort: {{ add $.Values.blockProducer.startingPorts $i $.Values.blockProducer.labelOffset }}
            protocol: TCP
          - name: metrics
            containerPort: 10000
        imagePullPolicy: Always
        volumeMounts:
        - name: wallet-keys
          mountPath: /root/wallet-keys
        - name: config-dir
          mountPath: /root/.coda-config
        {{- if $.Values.coda.genesis.active }}
        - name: genesis-constants
          mountPath: "/genesis_constants/"
        {{- end }}
      volumes:
      - name: private-keys
        secret:
          secretName: {{ $.Values.blockProducer.keySecretTemplatePrefix }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}-key
          defaultMode: 256
          items:
          - key: key
            path: key
          - key: pub
            path: key.pub
      - name: wallet-keys
        emptyDir: {}
      - name: config-dir
        emptyDir: {}
      {{- if $.Values.coda.genesis.active }}
      - name: genesis-constants
        configMap:
          name: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}-genesis-config
      {{- end }}
---
{{ if $.Values.coda.genesis.active -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}-genesis-config
  labels:
    app: {{ tpl $.Values.blockProducer.fullname $ }}-{{ add $i 1 $.Values.blockProducer.labelOffset }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
data:
  genesis_constants.json: |-
    {
        "txpool_max_size": {{ $.Values.coda.genesis.txpool_max_size }},
        "genesis_state_timestamp": {{ $.Values.coda.genesis.genesis_state_timestamp | quote}}
    }
{{- end}}
---
{{ end }}